# Generated by Django 3.2.8 on 2021-11-15 11:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0003_auto_20211115_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentarios',
            new_name='Comentarios',
        ),
    ]
