# Generated by Django 3.2.8 on 2021-11-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_rename_commentarios_comentarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
