# Generated by Django 3.2.8 on 2021-11-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='texto',
            new_name='text',
        ),
    ]
